export const CombatConfig = {
    biomes: [
        {
            id: 'spiders',
            name: 'Nido de Arañas',
            comingSoon: false,
            enemies: [
                {
                    id: 'spider-1',
                    name: 'Araña',
                    hp: 500,
                    defense: 1,
                    timerSec: 20,
                    isBoss: false,
                    requiresStars: null,
                    rarityPool: [{ rarity: 'rare', weight: 100 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 1 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 3 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 5 },
                    ],
                },
                {
                    id: 'spider-2',
                    name: 'Araña Tejedora',
                    hp: 800,
                    defense: 2,
                    timerSec: 20,
                    isBoss: false,
                    requiresStars: { enemyId: 'spider-1', stars: 1 },
                    rarityPool: [{ rarity: 'rare', weight: 80 }, { rarity: 'epic', weight: 20 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 2 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 5 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 8 },
                    ],
                },
                {
                    id: 'spider-3',
                    name: 'Araña Ancestral',
                    hp: 1600,
                    defense: 4,
                    timerSec: 20,
                    isBoss: false,
                    requiresStars: { enemyId: 'spider-2', stars: 1 },
                    rarityPool: [{ rarity: 'epic', weight: 90 }, { rarity: 'legendary', weight: 10 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 3 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 7 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 12 },
                    ],
                },
                {
                    id: 'spider-boss',
                    name: 'Reina Araña',
                    hp: 3200,
                    defense: 7,
                    timerSec: 25,
                    isBoss: true,
                    requiresStars: { enemyId: 'spider-3', stars: 2 },
                    rarityPool: [{ rarity: 'epic', weight: 70 }, { rarity: 'legendary', weight: 30 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 5 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 10 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 18 },
                    ],
                },
            ],
        },
        {
            id: 'bats',
            name: 'Caverna de Murciélagos',
            comingSoon: false,
            enemies: [
                {
                    id: 'bat-1',
                    name: 'Murciélago',
                    hp: 600,
                    defense: 5,
                    timerSec: 20,
                    isBoss: false,
                    goldPerCombo: 6,
                    requiresStars: null,
                    rarityPool: [{ rarity: 'rare', weight: 60 }, { rarity: 'epic', weight: 40 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 2 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 5 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 8 },
                    ],
                },
                {
                    id: 'bat-2',
                    name: 'Murciélago Oscuro',
                    hp: 1000,
                    defense: 7,
                    timerSec: 20,
                    isBoss: false,
                    goldPerCombo: 13,
                    requiresStars: { enemyId: 'bat-1', stars: 1 },
                    rarityPool: [{ rarity: 'rare', weight: 40 }, { rarity: 'epic', weight: 60 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 3 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 8 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 12 },
                    ],
                },
                {
                    id: 'bat-3',
                    name: 'Murciélago Anciano',
                    hp: 2500,
                    defense: 9,
                    timerSec: 20,
                    isBoss: false,
                    goldPerCombo: 20,
                    requiresStars: { enemyId: 'bat-2', stars: 1 },
                    rarityPool: [{ rarity: 'epic', weight: 70 }, { rarity: 'legendary', weight: 30 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 5 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 10 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 15 },
                    ],
                },
                {
                    id: 'bat-boss',
                    name: 'Murciélago Alfa',
                    hp: 3600,
                    defense: 13,
                    timerSec: 30,
                    isBoss: true,
                    goldPerCombo: 15,
                    requiresStars: { enemyId: 'bat-3', stars: 2 },
                    rarityPool: [{ rarity: 'epic', weight: 40 }, { rarity: 'legendary', weight: 60 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 5 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 12 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 20 },
                    ],
                },
            ],
        },
        {
            id: 'moles',
            name: 'Madriguera de Topos',
            comingSoon: false,
            enemies: [
                {
                    id: 'topo-1',
                    name: 'Topo',
                    hp: 750,
                    defense: 8,
                    timerSec: 20,
                    isBoss: false,
                    goldPerCombo: 6,
                    requiresStars: null,
                    rarityPool: [{ rarity: 'rare', weight: 60 }, { rarity: 'epic', weight: 40 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 2 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 5 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 8 },
                    ],
                },
                {
                    id: 'topo-2',
                    name: 'Topo Excavador',
                    hp: 1250,
                    defense: 10,
                    timerSec: 20,
                    isBoss: false,
                    goldPerCombo: 13,
                    requiresStars: { enemyId: 'topo-1', stars: 1 },
                    rarityPool: [{ rarity: 'rare', weight: 40 }, { rarity: 'epic', weight: 60 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 3 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 8 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 12 },
                    ],
                },
                {
                    id: 'topo-3',
                    name: 'Topo Anciano',
                    hp: 2900,
                    defense: 13,
                    timerSec: 20,
                    isBoss: false,
                    goldPerCombo: 20,
                    requiresStars: { enemyId: 'topo-2', stars: 1 },
                    rarityPool: [{ rarity: 'epic', weight: 70 }, { rarity: 'legendary', weight: 30 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 5 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 10 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 15 },
                    ],
                },
                {
                    id: 'topo-boss',
                    name: 'Topo Gigante',
                    hp: 4300,
                    defense: 15,
                    timerSec: 30,
                    isBoss: true,
                    goldPerCombo: 15,
                    requiresStars: { enemyId: 'topo-3', stars: 2 },
                    rarityPool: [{ rarity: 'epic', weight: 40 }, { rarity: 'legendary', weight: 60 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 5 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 12 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 20 },
                    ],
                },
            ],
        },
        {
            id: 'scorpions',
            name: 'Foso de Escorpiones',
            comingSoon: false,
            enemies: [
                {
                    id: 'scorpion-1',
                    name: 'Escorpión',
                    hp: 900,
                    defense: 8,
                    timerSec: 20,
                    isBoss: false,
                    goldPerCombo: 9,
                    requiresStars: null,
                    rarityPool: [{ rarity: 'rare', weight: 50 }, { rarity: 'epic', weight: 50 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 3 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 6 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 10 },
                    ],
                },
                {
                    id: 'scorpion-2',
                    name: 'Escorpión Venenoso',
                    hp: 1500,
                    defense: 12,
                    timerSec: 20,
                    isBoss: false,
                    goldPerCombo: 17,
                    requiresStars: { enemyId: 'scorpion-1', stars: 1 },
                    rarityPool: [{ rarity: 'epic', weight: 70 }, { rarity: 'legendary', weight: 30 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 4 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 9 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 14 },
                    ],
                },
                {
                    id: 'scorpion-3',
                    name: 'Escorpión Ancestral',
                    hp: 3200,
                    defense: 16,
                    timerSec: 25,
                    isBoss: false,
                    goldPerCombo: 17,
                    requiresStars: { enemyId: 'scorpion-2', stars: 1 },
                    rarityPool: [{ rarity: 'epic', weight: 50 }, { rarity: 'legendary', weight: 50 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 6 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 13 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 20 },
                    ],
                },
                {
                    id: 'scorpion-boss',
                    name: 'Rey Escorpión',
                    hp: 5000,
                    defense: 20,
                    timerSec: 30,
                    isBoss: true,
                    goldPerCombo: 21,
                    requiresStars: { enemyId: 'scorpion-3', stars: 2 },
                    rarityPool: [{ rarity: 'epic', weight: 30 }, { rarity: 'legendary', weight: 70 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 8 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 16 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 25 },
                    ],
                },
            ],
        },
    ],
};
