export const CombatConfig = {
    biomes: [
        {
            id: 'bats',
            name: 'Caverna de Murciélagos',
            comingSoon: false,
            enemies: [
                {
                    id: 'bat-1',
                    name: 'Murciélago',
                    hp: 350,
                    defense: 1,
                    timerSec: 20,
                    isBoss: false,
                    requiresStars: null,
                    rarityPool: [{ rarity: 'rare', weight: 100 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 1 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 3 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 5 },
                    ],
                },
                {
                    id: 'bat-2',
                    name: 'Murciélago Oscuro',
                    hp: 800,
                    defense: 2,
                    timerSec: 20,
                    isBoss: false,
                    requiresStars: { enemyId: 'bat-1', stars: 1 },
                    rarityPool: [{ rarity: 'rare', weight: 80 }, { rarity: 'epic', weight: 20 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 2 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 5 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 8 },
                    ],
                },
                {
                    id: 'bat-3',
                    name: 'Murciélago Anciano',
                    hp: 1600,
                    defense: 4,
                    timerSec: 20,
                    isBoss: false,
                    requiresStars: { enemyId: 'bat-2', stars: 1 },
                    rarityPool: [{ rarity: 'epic', weight: 90 }, { rarity: 'legendary', weight: 10 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 3 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 7 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 12 },
                    ],
                },
                {
                    id: 'bat-boss',
                    name: 'Murciélago Alfa',
                    hp: 3200,
                    defense: 7,
                    timerSec: 30,
                    isBoss: true,
                    requiresStars: { enemyId: 'bat-3', stars: 2 },
                    rarityPool: [{ rarity: 'epic', weight: 70 }, { rarity: 'legendary', weight: 30 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 5 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 10 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 18 },
                    ],
                },
            ],
        },
        {
            id: 'moles',
            name: 'Madriguera de Topos',
            comingSoon: false,
            enemies: [
                {
                    id: 'topo-1',
                    name: 'Topo',
                    hp: 600,
                    defense: 5,
                    timerSec: 20,
                    isBoss: false,
                    requiresStars: null,
                    rarityPool: [{ rarity: 'rare', weight: 60 }, { rarity: 'epic', weight: 40 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 2, gold: 1000 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 5, gold: 3000 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 8, gold: 5000 },
                    ],
                },
                {
                    id: 'topo-2',
                    name: 'Topo Excavador',
                    hp: 1000,
                    defense: 7,
                    timerSec: 20,
                    isBoss: false,
                    requiresStars: { enemyId: 'topo-1', stars: 1 },
                    rarityPool: [{ rarity: 'rare', weight: 40 }, { rarity: 'epic', weight: 60 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 3, gold: 3000 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 8, gold: 7000 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 12, gold: 12000 },
                    ],
                },
                {
                    id: 'topo-3',
                    name: 'Topo Anciano',
                    hp: 2500,
                    defense: 10,
                    timerSec: 20,
                    isBoss: false,
                    requiresStars: { enemyId: 'topo-2', stars: 1 },
                    rarityPool: [{ rarity: 'epic', weight: 70 }, { rarity: 'legendary', weight: 30 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 5, gold: 5000 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 10, gold: 12000 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 15, gold: 18000 },
                    ],
                },
                {
                    id: 'topo-boss',
                    name: 'Topo Gigante',
                    hp: 3600,
                    defense: 15,
                    timerSec: 30,
                    isBoss: true,
                    requiresStars: { enemyId: 'topo-3', stars: 2 },
                    rarityPool: [{ rarity: 'epic', weight: 40 }, { rarity: 'legendary', weight: 60 }],
                    rewardThresholds: [
                        { pct: 0.15, stars: 1, label: '1 estrella', shards: 5, gold: 8000 },
                        { pct: 0.50, stars: 2, label: '2 estrellas', shards: 12, gold: 18000 },
                        { pct: 0.95, stars: 3, label: '3 estrellas', shards: 20, gold: 30000 },
                    ],
                },
            ],
        },
    ],
};
